required:
  - id
  - geometry
properties:
  id:
    type: string
    minLength: 1
  geometry:
    type: geometry
  bbox:
    type: bounding-box
  area:
    type: uint32
    exclusiveMinimum: 0
  datetime:
    type: date-time
  expires:
    type: date-time
