$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
required:
  - fiboa_version
  - id
  - geometry
properties:
  fiboa_version:
    type: string
    enum:
      - 0.2.0
  fiboa_extensions:
    type: array
    items:
      type: string
      format: uri
  id:
    type: string
    minLength: 1
  collection:
    type: string
    minLength: 1
  category:
    type: array
    uniqueItems: true
    items:
      type: string
      enum:
        - conceptual
        - operational
        - economic
        - administrative
        - other
  geometry:
    type: geometry
  bbox:
    type: bounding-box
  area:
    type: float
    exclusiveMinimum: 0
    maximum: 100000
  perimeter:
    type: float
    exclusiveMinimum: 0
    maximum: 125000
  determination_datetime:
    type: date-time
  determination_method:
    type: string
    enum:
     - manual
     - driven
     - surveyed
     - auto-operation
     - auto-imagery
     - unknown
  determination_details:
    type: string
