properties:
  id:
    type: string
    minLength: 1
    required: true
  collection:
    type: string
    minLength: 1
  geometry:
    type: geometry
    required: true
  bbox:
    type: bounding-box
  area:
    type: uint32
    exclusiveMinimum: 0
    maximum: 1000000000
  determination_datetime:
    type: date-time
  determination_method:
    type: enum
    enum:
     - manual
     - driven
     - surveyed
     - administrative
     - auto-operation
     - auto-imagery
     - unknown
